### ISSUE TITLE
Latest Build

### ISSUE THREAD

**Issue by trismegistis** [MyEssentials/MyPermissions#4]
Caught exception from MyPermissions
java.lang.NoSuchMethodError: myessentials.Localization.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Class;)V
        at mypermissions.MyPermissions.preInit(

**Comment by MuresanSergiu** [comment]
Update MEC >.>

**Comment by stevestech** [comment]
Unless I am mistaken 1.7.10-1.13r is the latest release?

```
    UCH     MyEssentials-Core{1.7.10-1.13r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.13r-universal.jar)
    UCE     MyPermissions{1.7.10-0000r} [MyPermissions] (MyPermissions-1.7.10-34-dev.jar)
    UCE     MyTown2{1.7.10-0.2.0b} [MyTown 2] (MyTown2-1.7.10-0.2.0b.jar)
```

http://paste.ubuntu.com/12436575/

**Comment by MuresanSergiu** [comment]
Do not use latest build of MyPerms unless you update every other mods to the latest build. The build that works with MT2 0.2.0b and MEC 1.13r is 31-dev. Latest build (34-dev) requires latest build from both MEC and MT2.
Here you can find all the latest builds: https://ci.mineguild.net/

**Comment by trismegistis** [comment]
Thank you. Nice avatar afterwind
